version: '3.6'

networks:
  kafka-network:
    driver: bridge

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    networks:
      - kafka-network
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    networks:
      - kafka-network
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
